version: "3.9"
services:
  flask_app:
    image: m-ali/flask_app:1.0.0
    build: .
    ports:
      - "4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db 
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}